### ISSUE TITLE
coclist grep does not respect color values

### ISSUE THREAD

**Issue by Laumm** [neoclide/coc-lists#70]
### ENVIRONMENT
- macOS Mojave 10.14.6

- VIM - Vi IMproved 8.1

- ripgrep 11.0.2

- Item2 

- Oh-my-zsh

###  QUESTION
When i user CocList-grep to find word,the result does not respect color values .
<img width="946" alt="WechatIMG76" src="https://user-images.githubusercontent.com/42160960/72122195-147cf300-3398-11ea-8538-53e187fc1cd8.png">

**Comment by sparkcanon** [comment]
@Laumm this could be your colorscheme as it sometimes happens to me. Try badwolf and check if you see the issue again.

**Comment by arbitrary-dev** [comment]
Have the same issue, no coloring in CocLists and also the same for CocLocation. What makes it unable to identify which line is currently selected.

I guess it's due to highlighting groups being set up only for gui clients, not terminal:
```
:hi
...
CocListBlueRed xxx guifg=#458588 guibg=#cc241d
CocListFgBlue  xxx guifg=#458588
CocListBgBlue  xxx guibg=#458588
...
```

Should also have corresponding `cterm{fg,bg}` fields defined to support terminal vim clients.

@chemzqm Could you please tell which highligting group is being used for selected line? Tried `CocSelectedLine`, but it didn't help.

**Comment by chemzqm** [comment]
@adelarsq it's `:hi CursorLine`
